shell = "zsh"

# Ref: https://sheldon.cli.rs/Examples.html#deferred-loading-of-plugins-in-zsh
[templates]
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[plugins.environment]
local = "~/.config/zsh/environments"
apply = ["source"]

[plugins.compinit]
inline = "autoload -Uz compinit && zsh-defer compinit"

# Tools
[plugins.homebrew]
inline = "eval \"$(/opt/homebrew/bin/brew shellenv)\""

[plugins.homebrew-path]
local = "/opt/homebrew/bin"
apply = ["path"]

[plugins.homebrew-fpath]
local = "/opt/homebrew/share/zsh/site-functions"
apply = ["fpath"]

[plugins.homebrew-coreutils]
local = "/opt/homebrew/opt/coreutils/libexec/gnubin"
apply = ["path"]

[plugins.homebrew-gnu-sed]
local = "/opt/homebrew/opt/gnu-sed/libexec/gnubin"
apply = ["path"]

[plugins.kubectl-krew]
local = "~/.krew/bin"
apply = ["path"]

[plugins.coursier]
local = "~/.local/share/coursier/bin"
apply = ["path"]

[plugins.atuin]
inline = "[[ $commands[atuin] ]] && eval \"$(atuin init zsh)\""

[plugins.direnv]
inline = "[[ $commands[direnv] ]] && eval \"$(direnv hook zsh)\""

[plugins.mise]
inline = "[[ $commands[mise] ]] && eval \"$(mise activate zsh)\""

[plugins.rust]
inline = "[[ -f $HOME/.cargo/env ]] && zsh-defer source $HOME/.cargo/env"

[plugins.sdkman]
inline = "[[ -f $HOME/.sdkman/bin/sdkman-init.sh ]] && zsh-defer source $HOME/.sdkman/bin/sdkman-init.sh"

[plugins.starship]
inline = "[[ $commands[starship] ]] && eval \"$(starship init zsh)\""

# Plugins
[plugins.fast-syntax-highlighting]
github = "zdharma-continuum/fast-syntax-highlighting"
apply = ["defer"]

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
apply = ["defer"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
apply = ["defer"]

[plugins.abbr]
github = "olets/zsh-abbr"
use = ["zsh-abbr.plugin.zsh", "zsh-abbr.zsh"]

[plugins.anyframe]
github = "mollifier/anyframe"
apply = ["defer"]
hooks.post = "zsh-defer source $HOME/.config/zsh/hooks/anyframe.post.zsh"

# Configurations
[plugins.alias]
local = "~/.config/zsh"
use = ["alias.zsh"]
apply = ["source"]
