- hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - homebrew
    - homebrew-cask
    - macos
    - dotfiles
  vars:
    homebrew_repositories:
    homebrew_packages:
      - fish
      - mosh
      - node
      - stack
      - rust
      - go
      - python
      - python3
      - git
      - ghq
      - tig
      - fzf
      - ripgrep
      - neovim
    homebrew_cask_repositories:
      - homebrew/cask-versions
      - homebrew/cask-fonts
    homebrew_cask_packages:
      - google-chrome-canary
      - google-chrome
      - firefoxdeveloperedition
      - hyper
      - visual-studio-code
      - docker
      - discord
      - appcleaner
    homebrew_cask_fonts:
      - font-ubuntu
      - font-ubuntumono-nerd-font-mono
      - font-noto-sans-cjk-jp
      - font-noto-sans
      - font-noto-serif
      - font-source-han-sans
      - font-source-han-code-jp
    defaults_variables:
      - { domain: NSGlobalDomain, key: AppleICUForce24HourTime, type: bool, value: true }
      - { domain: NSGlobalDomain, key: InitialKeyRepeat, type: int, value: 15 }
      - { domain: NSGlobalDomain, key: KeyRepeat, type: int, value: 2 }
      - { domain: NSGlobalDomain, key: NSAutomaticDashSubstitutionEnabled, type: bool, value: false }
      - { domain: NSGlobalDomain, key: NSAutomaticQuoteSubstitutionEnabled, type: bool, value: false }
      - { domain: com.apple.AppleMultitouchTrackpad, key: Clicking, type: int, value: 1 }
      - { domain: com.apple.AppleMultitouchTrackpad, key: TrackpadThreeFingerDrag, type: bool, value: true }
      - { domain: com.apple.dock, key: showMissionControlGestureEnabled, type: bool, value: true }
      - { domain: com.apple.dock, key: showAppExposeGestureEnabled, type: bool, value: true }
      - { domain: com.apple.dock, key: showDesktopGestureEnabled, type: bool, value: true }
      - { domain: com.apple.dock, key: showLaunchpadGestureEnabled, type: bool, value: true }
      - { domain: com.apple.dock, key: autohide, type: bool, value: true }
      - { domain: com.apple.dock, key: persistent-apps, type: array, value: [] }
      - { domain: com.apple.dock, key: tilesize, type: int, value: 36 }
      - { domain: com.apple.finder, key: NewWindowTarget, type: string, value: 'PfHm' }
      - { domain: com.apple.finder, key: ShowStatusBar, type: bool, value: true }
      - { domain: com.apple.finder, key: ShowPathbar, type: bool, value: true }
      - { domain: com.apple.finder, key: ShowTabView, type: bool, value: true }
      - { domain: com.apple.finder, key: AppleShowAllFiles, type: bool, value: true }
      - { domain: com.apple.finder, key: FXPreferredViewStyle, type: string, value: 'clmv' }
      - { domain: com.apple.finder, key: FXPreferredGroupBy, type: string, value: 'Kind' }
      - { domain: com.apple.screensaver, key: askForPassword, type: int, value: 1 }
      - { domain: com.apple.screensaver, key: askForPasswordDelay, type: float, value: 5.0 }
      - { domain: com.apple.menuextra.battery, key: ShowPercent, type: string, value: 'YES' }
      - { domain: com.apple.menuextra.clock, key: DateFormat, type: string, value: 'EEE MMM d  h:mm:ss' }
      - { domain: com.microsoft.VSCode, key: ApplePressAndHoldEnabled, type: bool, value: false }
      - { domain: co.zeit.hyper, key: ApplePressAndHoldEnabled, type: bool, value: false }
    dotfiles:
      - { path: ~/dotfiles/fish/config.fish, dest: ~/.config/fish/config.fish }
      - { path: ~/dotfiles/fish/fishfile, dest: ~/.config/fish/fishfile }
      - { path: ~/dotfiles/hyper/hyper.js, dest: ~/.hyper.js }
      - { path: ~/dotfiles/vscode/settings.json, dest: ~/Library/Application Support/Code/User/settings.json }
      - { path: ~/dotfiles/vscode/locale.json, dest: ~/Library/Application Support/Code/User/locale.json }
