---
- name: Add external apt repositories
  apt_repository: repo={{ item }} state=present
  with_items: '{{ apt_repositories }}'
  when: '{{ apt_repositories }}'

- name: Add nodesource
  command: curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -

- name: Update apt-cache
  apt: update_cache=yes

- name: Install/Upgrade apt packages
  apt: >
    name={{ item.name | default(item) }}
    state={{ item.state | default('latest') }}
  with_items: '{{ apt_packages }}'
  when: '{{ apt_packages }}'

- name: Install Rust
  command: curl https://sh.rustup.rs -sSf | sh
