---
- name: Tap external Homebrew Cask repositories
  homebrew_tap: tap={{ item }} state=present
  with_items: '{{ homebrew_cask_repositories|default([]) }}'
  when: item is defined and item != ''

- name: Install/Upgrade Homebrew Cask packages
  homebrew_cask: >
    name={{ item.name|default(item) }}
    state={{ item.state|default('present') }}
  with_items: '{{ homebrew_cask_packages|default([]) }}'
  when: item is defined and item != ''

- name: Install/Upgrade Homebrew Cask fonts
  homebrew_cask: >
    name={{ item.name|default(item) }}
    state={{ item.state|default('present') }}
  with_items: '{{ homebrew_cask_fonts|default([]) }}'
  when: item is defined and item != ''
