---
- name: Create XDG config dir
  file: >
    path=~/.config
    state=directory

- name: Create fish config dir
  file: >
    path=~/.config/fish
    state=directory

- name: Create user bin dir
  file: >
    path=~/bin
    state=directory

- name: Symlink dotfiles
  file: >
    src={{ item.path }}
    dest={{ item.dest }}
    state=link
    force=yes
  with_items: '{{ dotfiles|default([]) }}'
  when: item.path is defined and item.dest is defined and item != ''

- shell: test -e ~/.config/fisherman; echo $?
  register: exist_fisherman

- name: Install fisherman
  command: curl -Lo ~/.config/fish/functions/fisher.fish --create-dirs https://git.io/fisher
  when: exist_fisherman.stdout == 1

- name: Install fish plugins
  command: fish -c "fisher"

- name: Install vscode extensions
  shell: |
    cat ~/dotfiles/vscode/extensions | while read line
    do
      code --install-extension $line
    done

- shell: test -e /usr/local/bin/im-select; echo $?
  register: exist_im-select

- name: Install VSCodeVim extensions
  shell: curl -Ls https://raw.githubusercontent.com/daipeihust/im-select/master/install_mac.sh | sh
  when: exist_im-select.stdout == 1