---
- name: Symlink dotfiles
  file: >
    src={{ item.path }}
    dest={{ item.dest }}
    state=link
    force=yes
  with_items: '{{ dotfiles }}'
  when: '{{ dotfiles }}'

- name: Install fisherman
  command: curl -Lo ~/.config/fish/functions/fisher.fish --create-dirs https://git.io/fisher
