---
# Create user directories
- name: Check user directories
  stat:
    path: "{{ item }}"
  register: directory_stats
  with_items:
  - ~/bin
  - ~/.config
  - ~/.cache
  - ~/.local
  - ~/.local/share
  - ~/.config/zsh
  - ~/.config/fish
  - ~/.config/nvim

- name: Create multiple directories without disturbing previous permissions
  file:
    path: "{{ item.item }}"
    state: directory
  when: item.stat.exists == false
  with_items:
  - "{{ directory_stats.results }}"

# symlink dotfiles
- name: Symlink dotfiles
  file: >
    src={{ item.path }}
    dest={{ item.dest }}
    state=link
    force=yes
  with_items: '{{ dotfiles|default([]) }}'
  when: item.path is defined and item.dest is defined and item != ''

# install fish plugins
# - stat:
#     path: ~/.config/fish/functions/fisher.fish
#   register: exist_fisherman

# - command: curl -Lo ~/.config/fish/functions/fisher.fish --create-dirs https://git.io/fisher
#   when: exist_fisherman.stat.exists == false

# - name: Install fish plugins
#   command: fish -c "fisher"

# install some runtimes
- name: Install some runtimes with asdf-vm
  shell: |
    asdf plugin-add {{ item.plugin }} && {{ item.post_add|default('echo "post-add command is nothing"') }}
    asdf install {{ item.plugin }} {{ item.version }}
    asdf global {{ item.plugin }} {{ item.version }} && {{ item.post_install|default('echo "post-install command is nothing"') }}
  with_items:
  - plugin: golang
    version: '1.14.4'
  - plugin: haskell
    version: '8.6.5'
  - plugin: java
    version: 'amazon-corretto-11.0.3.7.1'
  - plugin: maven
    version: '3.6.1'
  - plugin: nodejs
    version: '14.4.0'
    post_add: bash ~/.asdf/plugins/nodejs/bin/import-release-team-keyring
  - plugin: rust
    version: '1.44.0'
  - plugin: sbt
    version: '1.3.8'
  - plugin: terraform
    version: '0.12.5'

# install VSCode extensions
- name: Install vscode extensions
  shell: |
    cat ~/dotfiles/vscode/extensions | while read line
    do
      code --install-extension $line
    done

# install the VSCodeVim extension
- shell: which im-select; echo $?
  register: exist_imselect

- name: Install VSCodeVim extensions
  shell: curl -Ls https://raw.githubusercontent.com/daipeihust/im-select/master/install_mac.sh | sh
  when: exist_imselect.stdout == 1

# install nvim extension
- name: Install nvim extension
  shell: |
    curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
