---
# Create user directories
- name: Check user directories
  stat:
    path: "{{ item }}"
  register: directory_stats
  with_items:
  - ~/bin
  - ~/.config
  - ~/.cache
  - ~/.local
  - ~/.local/share
  - ~/.config/zsh
  - ~/.config/fish

- name: Create multiple directories without disturbing previous permissions
  file:
    path: "{{ item.item }}"
    state: directory
  when: item.stat.exists == false
  with_items:
  - "{{ directory_stats.results }}"

# symlink dotfiles
- name: Symlink dotfiles
  file: >
    src={{ item.path }}
    dest={{ item.dest }}
    state=link
    force=yes
  with_items: '{{ dotfiles|default([]) }}'
  when: item.path is defined and item.dest is defined and item != ''

# install fish plugins
- stat:
    path: ~/.config/fish/functions/fisher.fish
  register: exist_fisherman
 
- command: curl -Lo ~/.config/fish/functions/fisher.fish --create-dirs https://git.io/fisher
  when: exist_fisherman.stat.exists == false

- name: Install fish plugins
  command: fish -c "fisher"

# install VSCode extensions
- name: Install vscode extensions
  shell: |
    cat ~/dotfiles/vscode/extensions | while read line
    do
      code --install-extension $line
    done

# install the VSCodeVim extension
- shell: which im-select; echo $?
  register: exist_imselect

- name: Install VSCodeVim extensions
  shell: curl -Ls https://raw.githubusercontent.com/daipeihust/im-select/master/install_mac.sh | sh
  when: exist_imselect.stdout == 1