---
- name: Install Prezto
  command: zsh ~/dotfiles/zsh/prezto-setup.zsh creates=~/.zprezto

- name: Symlink dotfiles
  file: >
    src={{ item.path }}
    dest={{ item.dest }}
    state=link
    force=yes
  with_items: '{{ dotfiles }}'
  when: '{{ dotfiles }}'

- name: Setup ghq
  shell: git config --global ghq.root "~/src"

- name: Install powerline
  pip: name={{ item }}
  with_items: '{{ powerline }}'
  when: '{{ powerline }}'
