---
- name: Install Prezto
  script: ~/dotfiles/zsh/prezto-setup.zsh creates=~/.zprezto

# Oh-my-fish が消えた
# - name: Install Oh-my-fish
#   shell: curl -L github.com/oh-my-fish/oh-my-fish/raw/master/bin/install | sh

- name: Symlink dotfiles
  file: >
    src={{ item.path }}
    dest={{ item.dest }}
    state=link
    force=yes
  with_items: dotfiles
  when: dotfiles

- name: Install powerline
  pip: name={{ item }}
  with_items: powerline
  when: powerline
