---
- name: Set system defaults
  osx_defaults: >
    domain={{ item.domain }}
    key={{ item.key }}
    type={{ item.type }}
    value={{ item.value }}
  with_items: '{{ defaults_variables|default([]) }}'
  when: item.domain is defined and item.key is defined and item.type is defined and item.value is defined and item != ''

- shell: cat /etc/shells
  register: etc_shells

- name: Add `/etc/shells`
  lineinfile: 
    dest: /etc/shells
    line: '{{ item }}'
    state: present
    owner: root
    group: wheel
    mode: 0644
  become: true
  when: etc_shells.stdout.find('{{ item }}') == -1
  with_items:
    - /usr/local/bin/fish
    - /usr/local/bin/zsh

- name: Change default shell
  shell: chsh -s /usr/local/bin/zsh
  when: etc_shells.stdout.find('/usr/local/bin/zsh') == -1
