[font]
size = 16.0
bold = { family = "UbuntuMono Nerd Font", style = "Bold" }
bold_italic = { family = "UbuntuMono Nerd Font", style = "Bold Italic" }
italic = { family = "UbuntuMono Nerd Font", style = "Italic" }
normal = { family = "UbuntuMono Nerd Font", style = "Regular" }

[window]
decorations = "Buttonless"
padding = { x = 10, y = 10 }
option_as_alt = "Both"

[general]
import = ["~/.config/alacritty/themes/themes/nord.toml"]
