model = "gpt-5.4"
model_reasoning_effort = "high"
personality = "pragmatic"
service_tier = "fast"
suppress_unstable_features_warning = true
plan_mode_reasoning_effort = "high"
project_doc_fallback_filenames = ["CLAUDE.md"]

[features]
js_repl = true
multi_agent = true
prevent_idle_sleep = true
child_agents_md = true
memories = true
voice_transcription = true
